import json
from pathlib import Path

from .agent import InventoryAgent


# Load BOM JSON generated by Document Agent
bom_file = Path("output/APOLLO_TRACTORS_wheel_drive.json")

with open(bom_file, "r") as f:
    bom = json.load(f)

# Run Inventory Agent
agent = InventoryAgent()

result = agent.invoke(bom)

# Print status
print(result["status"])

# Print output file
print(result["output_file"])


from agents.inventory.agent import InventoryAgent

# Create Inventory Agent
agent = InventoryAgent()

# Visualize the graph
png = agent.graph.get_graph().draw_mermaid_png()

with open("inventory_graph.png", "wb") as f:
    f.write(png)

print("Inventory graph saved as inventory_graph.png")