from typing import TypedDict


class DecisionState(TypedDict):
    # Input from Inventory Agent
    inventory: dict

    # Output generated by Decision Agent
    decision: dict

    # Output JSON file path
    output_file: str

    # Execution status
    status: str

    # Error message (if any)
    error: str